FROM ubuntu:18.04

# RUN mkdir -p /home/metric/cpuMemUsage
# RUN mkdir -p /home/metric/networkUsage
# RUN apt update
# RUN apt-get install iputils-ping
# RUN apt-get install net-tools

# 실행 파일을 컨테이너 내부로 복사
COPY csd-metric-collector-tcpip-aarch64 /csd-metric-collector-tcpip-aarch64
# COPY csd-metric-collector-tcpip /csd-metric-collector-tcpip
# COPY test /test

# 실행 파일을 컨테이너 실행 명령으로 설정
# CMD ["/csd-metric-collector-tcpip-aarch64"]